### ISSUE TITLE
Signup page is not opening.

### ISSUE THREAD

**Issue by aaqansar** [SiddharthQss/TestRepo#1]
Description : Dummy Bug

Expected Result: Siddharth should not sleep.

Actual Result: Siddharth is sleeping.

**Comment by SiddharthQss** [comment]
Please check properly

**Comment by aaqansar** [comment]
Functionality is working fine, hence moving to Closed

**Comment by aaqansar** [comment]
@SiddharthQss Functionality is working fine, hence moving to Closed
